pipeline {
    agent {
        docker {
            image 'node:8'
            args '-p 3001:3001'
        }
    }
		enviroment {
			CI = 'true'
		}
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
				stage('Test') {
					steps{
						sh './jenkins/scripts/test.sh'
					}
				}
    }
}
